### ISSUE TITLE
One anim file broken.

### ISSUE THREAD

**Issue by pubemail** [Cyx69/TP_ThirdPersonNeuron#1]
The file "/Game/Mannequin/Character/Mesh/Mannequin_Neuron_AnimBlueprint" seems to be broken. UE4 throws "Error /Game/ThirdPersonCPP/Maps/ThirdPersonExampleMap : Can't find file for asset. /Game/Mannequin/Character/Mesh/Mannequin_Neuron_AnimBlueprint" on start. And this failed anim class causes one cast node in the Level Blueprint to be "bad cast node"(The one just after sequence then 1).

**Comment by Cyx69** [comment]
Hi pubemail. Thank you for the hint! 
I have just downloaded the actual master as a ZIP and also the asset you mentioned as a single file, but I get no error. May be there was an error while downloading. 
Please try again:
https://github.com/Cyx69/TP_ThirdPersonNeuron/archive/master.zip

**Comment by pubemail** [comment]
Thanks, Cyx69. But it's still not working.I have tried: download the zip pack again, and download the anim file separately, and git clone the repo. None of them works. Also, I tried seting the git HEAD back, the same error. 
I'm using windows 10.1 / UE 4.10.1 and 4.10.2 / Visual Studio Community 2015.
BTW, do I need to attach the Noitom devices before loading the project?

Error shows:
![capture](https://cloud.githubusercontent.com/assets/3525054/12267309/772fd7ea-b982-11e5-8ca6-5a866c0db029.PNG)

**Comment by Cyx69** [comment]
Hm, strange.
Could you have a look onto your harddisk how big the file "Mannequin_Neuron_AnimBlueprint.uasset" is? The file should have 5.244.696 Bytes at the moment.
Is the Blueprint shown in the Unreal Editor under "Content\Mannequin\Character\Mesh" and can you open it?
To your question:
No, the template tries to connect to the Noitom Axis Player when you start playing.

**Comment by pubemail** [comment]
Yeah, exactly 5.244.696 Bytes. And the Blueprint shows in the UE, the problem is I can't open it.

**Comment by Cyx69** [comment]
Hi pubemail. Good news.
I was able to reproduce the problem here if I open the project directly and not using it as a template (as I have written in the installation instructions).
If you want to open the project directly, just delete the file Config/TemplateDefs.ini and it should be fine.
Why Unreal throws this strange error in this case is still not clear for me. I will dig into it deeper.

**Comment by pubemail** [comment]
Yes! It works!
Thanks Cyx69! Thank you so much for your patience.
